<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Bonds.Sources</RootNamespace>
    <AssemblyName>bonds-dane</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bonds.Core\Bonds.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Bonds.Sources.Tests" />
  </ItemGroup>
</Project>
